name: Build and Release MO5 SDK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMOC and lwtools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmoc lwtools zip

      - name: Build SDK
        run: make export_sdk

      - name: Package SDK
        run: |
          cd sdk_mo5
          zip -r ../sdk_mo5.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: sdk_mo5.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}